### ISSUE TITLE
Command 'G' & short distance

### ISSUE THREAD

**Issue by lukicdarkoo** [Memristor-Robotics/pic-motion-driver#3]
There is a problem when we want to move a robot for short distance, the robot behaves very strangely. 

Command example:
```
G 0 0 1
G 1 0 1
```

**Comment by 112212** [comment]
fixed in commit [c181411c8e45d72d86d8c8b391e5a21c30dff7d5](https://github.com/Memristor-Robotics/pic-motion-driver/commit/c181411c8e45d72d86d8c8b391e5a21c30dff7d5)
